/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity.relationship;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserChannel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6362362305124801541L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserChannel\",\"namespace\":\"com.example.mediaservice.entity.relationship\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\",\"doc\":\"User ID\"},{\"name\":\"channelId\",\"type\":\"string\",\"doc\":\"Channel ID\"},{\"name\":\"UserChannelRelationship\",\"type\":{\"type\":\"enum\",\"name\":\"UserChannelRelationship\",\"symbols\":[\"CREATE\",\"JOIN\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserChannel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserChannel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserChannel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserChannel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserChannel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserChannel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserChannel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserChannel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserChannel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** User ID */
  private java.lang.CharSequence userId;
  /** Channel ID */
  private java.lang.CharSequence channelId;
  private com.example.mediaservice.entity.relationship.UserChannelRelationship UserChannelRelationship;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserChannel() {}

  /**
   * All-args constructor.
   * @param userId User ID
   * @param channelId Channel ID
   * @param UserChannelRelationship The new value for UserChannelRelationship
   */
  public UserChannel(java.lang.CharSequence userId, java.lang.CharSequence channelId, com.example.mediaservice.entity.relationship.UserChannelRelationship UserChannelRelationship) {
    this.userId = userId;
    this.channelId = channelId;
    this.UserChannelRelationship = UserChannelRelationship;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return channelId;
    case 2: return UserChannelRelationship;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: channelId = (java.lang.CharSequence)value$; break;
    case 2: UserChannelRelationship = (com.example.mediaservice.entity.relationship.UserChannelRelationship)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return User ID
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * User ID
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'channelId' field.
   * @return Channel ID
   */
  public java.lang.CharSequence getChannelId() {
    return channelId;
  }


  /**
   * Sets the value of the 'channelId' field.
   * Channel ID
   * @param value the value to set.
   */
  public void setChannelId(java.lang.CharSequence value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'UserChannelRelationship' field.
   * @return The value of the 'UserChannelRelationship' field.
   */
  public com.example.mediaservice.entity.relationship.UserChannelRelationship getUserChannelRelationship() {
    return UserChannelRelationship;
  }


  /**
   * Sets the value of the 'UserChannelRelationship' field.
   * @param value the value to set.
   */
  public void setUserChannelRelationship(com.example.mediaservice.entity.relationship.UserChannelRelationship value) {
    this.UserChannelRelationship = value;
  }

  /**
   * Creates a new UserChannel RecordBuilder.
   * @return A new UserChannel RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserChannel.Builder newBuilder() {
    return new com.example.mediaservice.entity.relationship.UserChannel.Builder();
  }

  /**
   * Creates a new UserChannel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserChannel RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserChannel.Builder newBuilder(com.example.mediaservice.entity.relationship.UserChannel.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.relationship.UserChannel.Builder();
    } else {
      return new com.example.mediaservice.entity.relationship.UserChannel.Builder(other);
    }
  }

  /**
   * Creates a new UserChannel RecordBuilder by copying an existing UserChannel instance.
   * @param other The existing instance to copy.
   * @return A new UserChannel RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserChannel.Builder newBuilder(com.example.mediaservice.entity.relationship.UserChannel other) {
    if (other == null) {
      return new com.example.mediaservice.entity.relationship.UserChannel.Builder();
    } else {
      return new com.example.mediaservice.entity.relationship.UserChannel.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserChannel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserChannel>
    implements org.apache.avro.data.RecordBuilder<UserChannel> {

    /** User ID */
    private java.lang.CharSequence userId;
    /** Channel ID */
    private java.lang.CharSequence channelId;
    private com.example.mediaservice.entity.relationship.UserChannelRelationship UserChannelRelationship;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.relationship.UserChannel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.UserChannelRelationship)) {
        this.UserChannelRelationship = data().deepCopy(fields()[2].schema(), other.UserChannelRelationship);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserChannel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.relationship.UserChannel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UserChannelRelationship)) {
        this.UserChannelRelationship = data().deepCopy(fields()[2].schema(), other.UserChannelRelationship);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * User ID
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * User ID
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * User ID
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * User ID
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'channelId' field.
      * Channel ID
      * @return The value.
      */
    public java.lang.CharSequence getChannelId() {
      return channelId;
    }


    /**
      * Sets the value of the 'channelId' field.
      * Channel ID
      * @param value The value of 'channelId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder setChannelId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.channelId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'channelId' field has been set.
      * Channel ID
      * @return True if the 'channelId' field has been set, false otherwise.
      */
    public boolean hasChannelId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'channelId' field.
      * Channel ID
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'UserChannelRelationship' field.
      * @return The value.
      */
    public com.example.mediaservice.entity.relationship.UserChannelRelationship getUserChannelRelationship() {
      return UserChannelRelationship;
    }


    /**
      * Sets the value of the 'UserChannelRelationship' field.
      * @param value The value of 'UserChannelRelationship'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder setUserChannelRelationship(com.example.mediaservice.entity.relationship.UserChannelRelationship value) {
      validate(fields()[2], value);
      this.UserChannelRelationship = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'UserChannelRelationship' field has been set.
      * @return True if the 'UserChannelRelationship' field has been set, false otherwise.
      */
    public boolean hasUserChannelRelationship() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'UserChannelRelationship' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserChannel.Builder clearUserChannelRelationship() {
      UserChannelRelationship = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserChannel build() {
      try {
        UserChannel record = new UserChannel();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.channelId = fieldSetFlags()[1] ? this.channelId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.UserChannelRelationship = fieldSetFlags()[2] ? this.UserChannelRelationship : (com.example.mediaservice.entity.relationship.UserChannelRelationship) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserChannel>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserChannel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserChannel>
    READER$ = (org.apache.avro.io.DatumReader<UserChannel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.channelId);

    out.writeEnum(this.UserChannelRelationship.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);

      this.UserChannelRelationship = com.example.mediaservice.entity.relationship.UserChannelRelationship.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
          break;

        case 2:
          this.UserChannelRelationship = com.example.mediaservice.entity.relationship.UserChannelRelationship.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (userId == null ? 0 : userId.hashCode());
    result = 31 * result + (channelId == null ? 0 : channelId.hashCode());
    result = 31 * result + (UserChannelRelationship == null ? 0 : ((java.lang.Enum) UserChannelRelationship).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof UserChannel)) {
      return false;
    }
    UserChannel other = (UserChannel) o;
    if (Utf8.compareSequences(this.userId, other.userId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.channelId, other.channelId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.UserChannelRelationship, other.UserChannelRelationship)) {
      return false;
    }
    return true;
  }
}










