/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity.relationship;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class UserGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -564126024783108314L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserGroup\",\"namespace\":\"com.example.mediaservice.entity.relationship\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"groupId\",\"type\":\"long\"},{\"name\":\"relationshipType\",\"type\":{\"type\":\"enum\",\"name\":\"RelationshipType\",\"symbols\":[\"CREATE\",\"JOIN\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserGroup> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserGroup> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserGroup> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserGroup to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserGroup from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserGroup instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long userId;
  private long groupId;
  private RelationshipType relationshipType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserGroup() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param groupId The new value for groupId
   * @param relationshipType The new value for relationshipType
   */
  public UserGroup(Long userId, Long groupId, RelationshipType relationshipType) {
    this.userId = userId;
    this.groupId = groupId;
    this.relationshipType = relationshipType;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return groupId;
    case 2: return relationshipType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: userId = (Long)value$; break;
    case 1: groupId = (Long)value$; break;
    case 2: relationshipType = (RelationshipType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return The value of the 'groupId' field.
   */
  public long getGroupId() {
    return groupId;
  }


  /**
   * Sets the value of the 'groupId' field.
   * @param value the value to set.
   */
  public void setGroupId(long value) {
    this.groupId = value;
  }

  /**
   * Gets the value of the 'relationshipType' field.
   * @return The value of the 'relationshipType' field.
   */
  public RelationshipType getRelationshipType() {
    return relationshipType;
  }


  /**
   * Sets the value of the 'relationshipType' field.
   * @param value the value to set.
   */
  public void setRelationshipType(RelationshipType value) {
    this.relationshipType = value;
  }

  /**
   * Creates a new UserGroup RecordBuilder.
   * @return A new UserGroup RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing UserGroup instance.
   * @param other The existing instance to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static Builder newBuilder(UserGroup other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for UserGroup instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserGroup>
    implements org.apache.avro.data.RecordBuilder<UserGroup> {

    private long userId;
    private long groupId;
    private RelationshipType relationshipType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.relationshipType)) {
        this.relationshipType = data().deepCopy(fields()[2].schema(), other.relationshipType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(UserGroup other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.relationshipType)) {
        this.relationshipType = data().deepCopy(fields()[2].schema(), other.relationshipType);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groupId' field.
      * @return The value.
      */
    public long getGroupId() {
      return groupId;
    }


    /**
      * Sets the value of the 'groupId' field.
      * @param value The value of 'groupId'.
      * @return This builder.
      */
    public Builder setGroupId(long value) {
      validate(fields()[1], value);
      this.groupId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groupId' field has been set.
      * @return True if the 'groupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groupId' field.
      * @return This builder.
      */
    public Builder clearGroupId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'relationshipType' field.
      * @return The value.
      */
    public RelationshipType getRelationshipType() {
      return relationshipType;
    }


    /**
      * Sets the value of the 'relationshipType' field.
      * @param value The value of 'relationshipType'.
      * @return This builder.
      */
    public Builder setRelationshipType(RelationshipType value) {
      validate(fields()[2], value);
      this.relationshipType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'relationshipType' field has been set.
      * @return True if the 'relationshipType' field has been set, false otherwise.
      */
    public boolean hasRelationshipType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'relationshipType' field.
      * @return This builder.
      */
    public Builder clearRelationshipType() {
      relationshipType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserGroup build() {
      try {
        UserGroup record = new UserGroup();
        record.userId = fieldSetFlags()[0] ? this.userId : (Long) defaultValue(fields()[0]);
        record.groupId = fieldSetFlags()[1] ? this.groupId : (Long) defaultValue(fields()[1]);
        record.relationshipType = fieldSetFlags()[2] ? this.relationshipType : (RelationshipType) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserGroup>
    READER$ = (org.apache.avro.io.DatumReader<UserGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeLong(this.groupId);

    out.writeEnum(this.relationshipType.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.groupId = in.readLong();

      this.relationshipType = RelationshipType.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.groupId = in.readLong();
          break;

        case 2:
          this.relationshipType = RelationshipType.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Long.hashCode(userId);
    result = 31 * result + Long.hashCode(groupId);
    result = 31 * result + (relationshipType == null ? 0 : ((Enum) relationshipType).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof UserGroup)) {
      return false;
    }
    UserGroup other = (UserGroup) o;
    if (this.userId != other.userId) {
      return false;
    }
    if (this.groupId != other.groupId) {
      return false;
    }
    if (!java.util.Objects.equals(this.relationshipType, other.relationshipType)) {
      return false;
    }
    return true;
  }
}










