/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity.relationship;
@org.apache.avro.specific.AvroGenerated
public enum UserChannelRelationship implements org.apache.avro.generic.GenericEnumSymbol<UserChannelRelationship> {
  CREATE, JOIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserChannelRelationship\",\"namespace\":\"com.example.mediaservice.entity.relationship\",\"symbols\":[\"CREATE\",\"JOIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
