/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity.relationship;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8014648496299711002L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserGroup\",\"namespace\":\"com.example.mediaservice.entity.relationship\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"groupId\",\"type\":\"string\"},{\"name\":\"UserGroupRelationship\",\"type\":{\"type\":\"enum\",\"name\":\"UserGroupRelationship\",\"symbols\":[\"CREATE\",\"JOIN\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserGroup> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserGroup> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserGroup> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserGroup to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserGroup from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserGroup instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userId;
  private java.lang.CharSequence groupId;
  private com.example.mediaservice.entity.relationship.UserGroupRelationship UserGroupRelationship;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserGroup() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param groupId The new value for groupId
   * @param UserGroupRelationship The new value for UserGroupRelationship
   */
  public UserGroup(java.lang.CharSequence userId, java.lang.CharSequence groupId, com.example.mediaservice.entity.relationship.UserGroupRelationship UserGroupRelationship) {
    this.userId = userId;
    this.groupId = groupId;
    this.UserGroupRelationship = UserGroupRelationship;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return groupId;
    case 2: return UserGroupRelationship;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: groupId = (java.lang.CharSequence)value$; break;
    case 2: UserGroupRelationship = (com.example.mediaservice.entity.relationship.UserGroupRelationship)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return The value of the 'groupId' field.
   */
  public java.lang.CharSequence getGroupId() {
    return groupId;
  }


  /**
   * Sets the value of the 'groupId' field.
   * @param value the value to set.
   */
  public void setGroupId(java.lang.CharSequence value) {
    this.groupId = value;
  }

  /**
   * Gets the value of the 'UserGroupRelationship' field.
   * @return The value of the 'UserGroupRelationship' field.
   */
  public com.example.mediaservice.entity.relationship.UserGroupRelationship getUserGroupRelationship() {
    return UserGroupRelationship;
  }


  /**
   * Sets the value of the 'UserGroupRelationship' field.
   * @param value the value to set.
   */
  public void setUserGroupRelationship(com.example.mediaservice.entity.relationship.UserGroupRelationship value) {
    this.UserGroupRelationship = value;
  }

  /**
   * Creates a new UserGroup RecordBuilder.
   * @return A new UserGroup RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserGroup.Builder newBuilder() {
    return new com.example.mediaservice.entity.relationship.UserGroup.Builder();
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserGroup.Builder newBuilder(com.example.mediaservice.entity.relationship.UserGroup.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.relationship.UserGroup.Builder();
    } else {
      return new com.example.mediaservice.entity.relationship.UserGroup.Builder(other);
    }
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing UserGroup instance.
   * @param other The existing instance to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static com.example.mediaservice.entity.relationship.UserGroup.Builder newBuilder(com.example.mediaservice.entity.relationship.UserGroup other) {
    if (other == null) {
      return new com.example.mediaservice.entity.relationship.UserGroup.Builder();
    } else {
      return new com.example.mediaservice.entity.relationship.UserGroup.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserGroup instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserGroup>
    implements org.apache.avro.data.RecordBuilder<UserGroup> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence groupId;
    private com.example.mediaservice.entity.relationship.UserGroupRelationship UserGroupRelationship;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.relationship.UserGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.UserGroupRelationship)) {
        this.UserGroupRelationship = data().deepCopy(fields()[2].schema(), other.UserGroupRelationship);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.relationship.UserGroup other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UserGroupRelationship)) {
        this.UserGroupRelationship = data().deepCopy(fields()[2].schema(), other.UserGroupRelationship);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groupId' field.
      * @return The value.
      */
    public java.lang.CharSequence getGroupId() {
      return groupId;
    }


    /**
      * Sets the value of the 'groupId' field.
      * @param value The value of 'groupId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder setGroupId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.groupId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groupId' field has been set.
      * @return True if the 'groupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groupId' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder clearGroupId() {
      groupId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'UserGroupRelationship' field.
      * @return The value.
      */
    public com.example.mediaservice.entity.relationship.UserGroupRelationship getUserGroupRelationship() {
      return UserGroupRelationship;
    }


    /**
      * Sets the value of the 'UserGroupRelationship' field.
      * @param value The value of 'UserGroupRelationship'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder setUserGroupRelationship(com.example.mediaservice.entity.relationship.UserGroupRelationship value) {
      validate(fields()[2], value);
      this.UserGroupRelationship = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'UserGroupRelationship' field has been set.
      * @return True if the 'UserGroupRelationship' field has been set, false otherwise.
      */
    public boolean hasUserGroupRelationship() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'UserGroupRelationship' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.relationship.UserGroup.Builder clearUserGroupRelationship() {
      UserGroupRelationship = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserGroup build() {
      try {
        UserGroup record = new UserGroup();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.groupId = fieldSetFlags()[1] ? this.groupId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.UserGroupRelationship = fieldSetFlags()[2] ? this.UserGroupRelationship : (com.example.mediaservice.entity.relationship.UserGroupRelationship) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserGroup>
    READER$ = (org.apache.avro.io.DatumReader<UserGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.groupId);

    out.writeEnum(this.UserGroupRelationship.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);

      this.UserGroupRelationship = com.example.mediaservice.entity.relationship.UserGroupRelationship.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);
          break;

        case 2:
          this.UserGroupRelationship = com.example.mediaservice.entity.relationship.UserGroupRelationship.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (userId == null ? 0 : userId.hashCode());
    result = 31 * result + (groupId == null ? 0 : groupId.hashCode());
    result = 31 * result + (UserGroupRelationship == null ? 0 : ((java.lang.Enum) UserGroupRelationship).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof UserGroup)) {
      return false;
    }
    UserGroup other = (UserGroup) o;
    if (Utf8.compareSequences(this.userId, other.userId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.groupId, other.groupId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.UserGroupRelationship, other.UserGroupRelationship)) {
      return false;
    }
    return true;
  }
}










