/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Channel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1446502077321519561L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Channel\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"channelId\",\"type\":\"string\",\"doc\":\"Channel ID as primary key\"},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Channel name (e.g., general, random, etc.)\"},{\"name\":\"groupId\",\"type\":\"string\",\"doc\":\"Group ID that this channel belongs to\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Channel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Channel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Channel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Channel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Channel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Channel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Channel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Channel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Channel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Channel ID as primary key */
  private java.lang.CharSequence channelId;
  /** Channel name (e.g., general, random, etc.) */
  private java.lang.CharSequence name;
  /** Group ID that this channel belongs to */
  private java.lang.CharSequence groupId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Channel() {}

  /**
   * All-args constructor.
   * @param channelId Channel ID as primary key
   * @param name Channel name (e.g., general, random, etc.)
   * @param groupId Group ID that this channel belongs to
   */
  public Channel(java.lang.CharSequence channelId, java.lang.CharSequence name, java.lang.CharSequence groupId) {
    this.channelId = channelId;
    this.name = name;
    this.groupId = groupId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channelId;
    case 1: return name;
    case 2: return groupId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channelId = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: groupId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'channelId' field.
   * @return Channel ID as primary key
   */
  public java.lang.CharSequence getChannelId() {
    return channelId;
  }


  /**
   * Sets the value of the 'channelId' field.
   * Channel ID as primary key
   * @param value the value to set.
   */
  public void setChannelId(java.lang.CharSequence value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Channel name (e.g., general, random, etc.)
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Channel name (e.g., general, random, etc.)
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return Group ID that this channel belongs to
   */
  public java.lang.CharSequence getGroupId() {
    return groupId;
  }


  /**
   * Sets the value of the 'groupId' field.
   * Group ID that this channel belongs to
   * @param value the value to set.
   */
  public void setGroupId(java.lang.CharSequence value) {
    this.groupId = value;
  }

  /**
   * Creates a new Channel RecordBuilder.
   * @return A new Channel RecordBuilder
   */
  public static com.example.mediaservice.entity.Channel.Builder newBuilder() {
    return new com.example.mediaservice.entity.Channel.Builder();
  }

  /**
   * Creates a new Channel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Channel RecordBuilder
   */
  public static com.example.mediaservice.entity.Channel.Builder newBuilder(com.example.mediaservice.entity.Channel.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Channel.Builder();
    } else {
      return new com.example.mediaservice.entity.Channel.Builder(other);
    }
  }

  /**
   * Creates a new Channel RecordBuilder by copying an existing Channel instance.
   * @param other The existing instance to copy.
   * @return A new Channel RecordBuilder
   */
  public static com.example.mediaservice.entity.Channel.Builder newBuilder(com.example.mediaservice.entity.Channel other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Channel.Builder();
    } else {
      return new com.example.mediaservice.entity.Channel.Builder(other);
    }
  }

  /**
   * RecordBuilder for Channel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Channel>
    implements org.apache.avro.data.RecordBuilder<Channel> {

    /** Channel ID as primary key */
    private java.lang.CharSequence channelId;
    /** Channel name (e.g., general, random, etc.) */
    private java.lang.CharSequence name;
    /** Group ID that this channel belongs to */
    private java.lang.CharSequence groupId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.Channel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.groupId)) {
        this.groupId = data().deepCopy(fields()[2].schema(), other.groupId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Channel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.Channel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.channelId)) {
        this.channelId = data().deepCopy(fields()[0].schema(), other.channelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.groupId)) {
        this.groupId = data().deepCopy(fields()[2].schema(), other.groupId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'channelId' field.
      * Channel ID as primary key
      * @return The value.
      */
    public java.lang.CharSequence getChannelId() {
      return channelId;
    }


    /**
      * Sets the value of the 'channelId' field.
      * Channel ID as primary key
      * @param value The value of 'channelId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder setChannelId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.channelId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'channelId' field has been set.
      * Channel ID as primary key
      * @return True if the 'channelId' field has been set, false otherwise.
      */
    public boolean hasChannelId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'channelId' field.
      * Channel ID as primary key
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Channel name (e.g., general, random, etc.)
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Channel name (e.g., general, random, etc.)
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Channel name (e.g., general, random, etc.)
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Channel name (e.g., general, random, etc.)
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'groupId' field.
      * Group ID that this channel belongs to
      * @return The value.
      */
    public java.lang.CharSequence getGroupId() {
      return groupId;
    }


    /**
      * Sets the value of the 'groupId' field.
      * Group ID that this channel belongs to
      * @param value The value of 'groupId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder setGroupId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.groupId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'groupId' field has been set.
      * Group ID that this channel belongs to
      * @return True if the 'groupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'groupId' field.
      * Group ID that this channel belongs to
      * @return This builder.
      */
    public com.example.mediaservice.entity.Channel.Builder clearGroupId() {
      groupId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Channel build() {
      try {
        Channel record = new Channel();
        record.channelId = fieldSetFlags()[0] ? this.channelId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.groupId = fieldSetFlags()[2] ? this.groupId : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Channel>
    WRITER$ = (org.apache.avro.io.DatumWriter<Channel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Channel>
    READER$ = (org.apache.avro.io.DatumReader<Channel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.channelId);

    out.writeString(this.name);

    out.writeString(this.groupId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (channelId == null ? 0 : channelId.hashCode());
    result = 31 * result + (name == null ? 0 : name.hashCode());
    result = 31 * result + (groupId == null ? 0 : groupId.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Channel)) {
      return false;
    }
    Channel other = (Channel) o;
    if (Utf8.compareSequences(this.channelId, other.channelId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.name, other.name) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.groupId, other.groupId) != 0) {
      return false;
    }
    return true;
  }
}










