/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;
@org.apache.avro.specific.AvroGenerated
public enum CommentEventType implements org.apache.avro.generic.GenericEnumSymbol<CommentEventType> {
  CREATED, UPDATED, DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CommentEventType\",\"namespace\":\"com.example.mediaservice.entity\",\"symbols\":[\"CREATED\",\"UPDATED\",\"DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
