/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Comment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4756469920516509511L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Comment\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"Comment ID as primary key\"},{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"CommentEventType\",\"symbols\":[\"CREATED\",\"UPDATED\",\"DELETED\"]},\"default\":\"CREATED\"},{\"name\":\"author\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"email\",\"type\":\"string\",\"doc\":\"Email as primary key\"},{\"name\":\"dateOfBirth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"avatarUrl\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"occupation\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"version\",\"type\":[\"null\",\"int\"],\"doc\":\"Version for optimistic locking\",\"default\":null}]}],\"doc\":\"Email of the comment author\"},{\"name\":\"postId\",\"type\":[\"null\",\"string\"],\"doc\":\"Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post\",\"default\":null},{\"name\":\"parentId\",\"type\":[\"null\",\"string\"],\"doc\":\"ID của comment cha nếu đây là reply cho comment khác\",\"default\":null},{\"name\":\"content\",\"type\":\"string\",\"doc\":\"Comment content\"},{\"name\":\"createdAt\",\"type\":\"long\",\"doc\":\"Timestamp of post creation\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Comment> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Comment> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Comment> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Comment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Comment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Comment to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Comment from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Comment instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Comment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Comment ID as primary key */
  private java.lang.CharSequence id;
  private com.example.mediaservice.entity.CommentEventType eventType;
  /** Email of the comment author */
  private com.example.mediaservice.entity.User author;
  /** Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post */
  private java.lang.CharSequence postId;
  /** ID của comment cha nếu đây là reply cho comment khác */
  private java.lang.CharSequence parentId;
  /** Comment content */
  private java.lang.CharSequence content;
  /** Timestamp of post creation */
  private long createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Comment() {}

  /**
   * All-args constructor.
   * @param id Comment ID as primary key
   * @param eventType The new value for eventType
   * @param author Email of the comment author
   * @param postId Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
   * @param parentId ID của comment cha nếu đây là reply cho comment khác
   * @param content Comment content
   * @param createdAt Timestamp of post creation
   */
  public Comment(java.lang.CharSequence id, com.example.mediaservice.entity.CommentEventType eventType, com.example.mediaservice.entity.User author, java.lang.CharSequence postId, java.lang.CharSequence parentId, java.lang.CharSequence content, java.lang.Long createdAt) {
    this.id = id;
    this.eventType = eventType;
    this.author = author;
    this.postId = postId;
    this.parentId = parentId;
    this.content = content;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return eventType;
    case 2: return author;
    case 3: return postId;
    case 4: return parentId;
    case 5: return content;
    case 6: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: eventType = (com.example.mediaservice.entity.CommentEventType)value$; break;
    case 2: author = (com.example.mediaservice.entity.User)value$; break;
    case 3: postId = (java.lang.CharSequence)value$; break;
    case 4: parentId = (java.lang.CharSequence)value$; break;
    case 5: content = (java.lang.CharSequence)value$; break;
    case 6: createdAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Comment ID as primary key
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Comment ID as primary key
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public com.example.mediaservice.entity.CommentEventType getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(com.example.mediaservice.entity.CommentEventType value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'author' field.
   * @return Email of the comment author
   */
  public com.example.mediaservice.entity.User getAuthor() {
    return author;
  }


  /**
   * Sets the value of the 'author' field.
   * Email of the comment author
   * @param value the value to set.
   */
  public void setAuthor(com.example.mediaservice.entity.User value) {
    this.author = value;
  }

  /**
   * Gets the value of the 'postId' field.
   * @return Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
   */
  public java.lang.CharSequence getPostId() {
    return postId;
  }


  /**
   * Sets the value of the 'postId' field.
   * Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
   * @param value the value to set.
   */
  public void setPostId(java.lang.CharSequence value) {
    this.postId = value;
  }

  /**
   * Gets the value of the 'parentId' field.
   * @return ID của comment cha nếu đây là reply cho comment khác
   */
  public java.lang.CharSequence getParentId() {
    return parentId;
  }


  /**
   * Sets the value of the 'parentId' field.
   * ID của comment cha nếu đây là reply cho comment khác
   * @param value the value to set.
   */
  public void setParentId(java.lang.CharSequence value) {
    this.parentId = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return Comment content
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * Comment content
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Timestamp of post creation
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Timestamp of post creation
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Creates a new Comment RecordBuilder.
   * @return A new Comment RecordBuilder
   */
  public static com.example.mediaservice.entity.Comment.Builder newBuilder() {
    return new com.example.mediaservice.entity.Comment.Builder();
  }

  /**
   * Creates a new Comment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Comment RecordBuilder
   */
  public static com.example.mediaservice.entity.Comment.Builder newBuilder(com.example.mediaservice.entity.Comment.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Comment.Builder();
    } else {
      return new com.example.mediaservice.entity.Comment.Builder(other);
    }
  }

  /**
   * Creates a new Comment RecordBuilder by copying an existing Comment instance.
   * @param other The existing instance to copy.
   * @return A new Comment RecordBuilder
   */
  public static com.example.mediaservice.entity.Comment.Builder newBuilder(com.example.mediaservice.entity.Comment other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Comment.Builder();
    } else {
      return new com.example.mediaservice.entity.Comment.Builder(other);
    }
  }

  /**
   * RecordBuilder for Comment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Comment>
    implements org.apache.avro.data.RecordBuilder<Comment> {

    /** Comment ID as primary key */
    private java.lang.CharSequence id;
    private com.example.mediaservice.entity.CommentEventType eventType;
    /** Email of the comment author */
    private com.example.mediaservice.entity.User author;
    private com.example.mediaservice.entity.User.Builder authorBuilder;
    /** Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post */
    private java.lang.CharSequence postId;
    /** ID của comment cha nếu đây là reply cho comment khác */
    private java.lang.CharSequence parentId;
    /** Comment content */
    private java.lang.CharSequence content;
    /** Timestamp of post creation */
    private long createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.Comment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.author)) {
        this.author = data().deepCopy(fields()[2].schema(), other.author);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasAuthorBuilder()) {
        this.authorBuilder = com.example.mediaservice.entity.User.newBuilder(other.getAuthorBuilder());
      }
      if (isValidValue(fields()[3], other.postId)) {
        this.postId = data().deepCopy(fields()[3].schema(), other.postId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.parentId)) {
        this.parentId = data().deepCopy(fields()[4].schema(), other.parentId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.content)) {
        this.content = data().deepCopy(fields()[5].schema(), other.content);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Comment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.Comment other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.author)) {
        this.author = data().deepCopy(fields()[2].schema(), other.author);
        fieldSetFlags()[2] = true;
      }
      this.authorBuilder = null;
      if (isValidValue(fields()[3], other.postId)) {
        this.postId = data().deepCopy(fields()[3].schema(), other.postId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.parentId)) {
        this.parentId = data().deepCopy(fields()[4].schema(), other.parentId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.content)) {
        this.content = data().deepCopy(fields()[5].schema(), other.content);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Comment ID as primary key
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Comment ID as primary key
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Comment ID as primary key
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Comment ID as primary key
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public com.example.mediaservice.entity.CommentEventType getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setEventType(com.example.mediaservice.entity.CommentEventType value) {
      validate(fields()[1], value);
      this.eventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'author' field.
      * Email of the comment author
      * @return The value.
      */
    public com.example.mediaservice.entity.User getAuthor() {
      return author;
    }


    /**
      * Sets the value of the 'author' field.
      * Email of the comment author
      * @param value The value of 'author'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setAuthor(com.example.mediaservice.entity.User value) {
      validate(fields()[2], value);
      this.authorBuilder = null;
      this.author = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'author' field has been set.
      * Email of the comment author
      * @return True if the 'author' field has been set, false otherwise.
      */
    public boolean hasAuthor() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'author' field and creates one if it doesn't exist yet.
     * Email of the comment author
     * @return This builder.
     */
    public com.example.mediaservice.entity.User.Builder getAuthorBuilder() {
      if (authorBuilder == null) {
        if (hasAuthor()) {
          setAuthorBuilder(com.example.mediaservice.entity.User.newBuilder(author));
        } else {
          setAuthorBuilder(com.example.mediaservice.entity.User.newBuilder());
        }
      }
      return authorBuilder;
    }

    /**
     * Sets the Builder instance for the 'author' field
     * Email of the comment author
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.mediaservice.entity.Comment.Builder setAuthorBuilder(com.example.mediaservice.entity.User.Builder value) {
      clearAuthor();
      authorBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'author' field has an active Builder instance
     * Email of the comment author
     * @return True if the 'author' field has an active Builder instance
     */
    public boolean hasAuthorBuilder() {
      return authorBuilder != null;
    }

    /**
      * Clears the value of the 'author' field.
      * Email of the comment author
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearAuthor() {
      author = null;
      authorBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'postId' field.
      * Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
      * @return The value.
      */
    public java.lang.CharSequence getPostId() {
      return postId;
    }


    /**
      * Sets the value of the 'postId' field.
      * Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
      * @param value The value of 'postId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setPostId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.postId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'postId' field has been set.
      * Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
      * @return True if the 'postId' field has been set, false otherwise.
      */
    public boolean hasPostId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'postId' field.
      * Nếu null thì đây là comment trả lời cho comment khác, nếu có giá trị thì đây là comment cho bài post
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearPostId() {
      postId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'parentId' field.
      * ID của comment cha nếu đây là reply cho comment khác
      * @return The value.
      */
    public java.lang.CharSequence getParentId() {
      return parentId;
    }


    /**
      * Sets the value of the 'parentId' field.
      * ID của comment cha nếu đây là reply cho comment khác
      * @param value The value of 'parentId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setParentId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.parentId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'parentId' field has been set.
      * ID của comment cha nếu đây là reply cho comment khác
      * @return True if the 'parentId' field has been set, false otherwise.
      */
    public boolean hasParentId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'parentId' field.
      * ID của comment cha nếu đây là reply cho comment khác
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearParentId() {
      parentId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * Comment content
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * Comment content
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.content = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * Comment content
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'content' field.
      * Comment content
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearContent() {
      content = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Timestamp of post creation
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Timestamp of post creation
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder setCreatedAt(long value) {
      validate(fields()[6], value);
      this.createdAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Timestamp of post creation
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Timestamp of post creation
      * @return This builder.
      */
    public com.example.mediaservice.entity.Comment.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Comment build() {
      try {
        Comment record = new Comment();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.eventType = fieldSetFlags()[1] ? this.eventType : (com.example.mediaservice.entity.CommentEventType) defaultValue(fields()[1]);
        if (authorBuilder != null) {
          try {
            record.author = this.authorBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("author"));
            throw e;
          }
        } else {
          record.author = fieldSetFlags()[2] ? this.author : (com.example.mediaservice.entity.User) defaultValue(fields()[2]);
        }
        record.postId = fieldSetFlags()[3] ? this.postId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.parentId = fieldSetFlags()[4] ? this.parentId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.content = fieldSetFlags()[5] ? this.content : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.createdAt = fieldSetFlags()[6] ? this.createdAt : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Comment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Comment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Comment>
    READER$ = (org.apache.avro.io.DatumReader<Comment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeEnum(this.eventType.ordinal());

    if (this.author == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.author.customEncode(out);
    }

    if (this.postId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.postId);
    }

    if (this.parentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.parentId);
    }

    out.writeString(this.content);

    out.writeLong(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.eventType = com.example.mediaservice.entity.CommentEventType.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.author = null;
      } else {
        if (this.author == null) {
          this.author = new com.example.mediaservice.entity.User();
        }
        this.author.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.postId = null;
      } else {
        this.postId = in.readString(this.postId instanceof Utf8 ? (Utf8)this.postId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.parentId = null;
      } else {
        this.parentId = in.readString(this.parentId instanceof Utf8 ? (Utf8)this.parentId : null);
      }

      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

      this.createdAt = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.eventType = com.example.mediaservice.entity.CommentEventType.values()[in.readEnum()];
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.author = null;
          } else {
            if (this.author == null) {
              this.author = new com.example.mediaservice.entity.User();
            }
            this.author.customDecode(in);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.postId = null;
          } else {
            this.postId = in.readString(this.postId instanceof Utf8 ? (Utf8)this.postId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.parentId = null;
          } else {
            this.parentId = in.readString(this.parentId instanceof Utf8 ? (Utf8)this.parentId : null);
          }
          break;

        case 5:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        case 6:
          this.createdAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (eventType == null ? 0 : ((java.lang.Enum) eventType).ordinal());
    result = 31 * result + (author == null ? 0 : author.hashCode());
    result = 31 * result + (postId == null ? 0 : postId.hashCode());
    result = 31 * result + (parentId == null ? 0 : parentId.hashCode());
    result = 31 * result + (content == null ? 0 : content.hashCode());
    result = 31 * result + Long.hashCode(createdAt);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Comment)) {
      return false;
    }
    Comment other = (Comment) o;
    if (Utf8.compareSequences(this.id, other.id) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventType, other.eventType)) {
      return false;
    }
    if (!java.util.Objects.equals(this.author, other.author)) {
      return false;
    }
    if (Utf8.compareSequences(this.postId, other.postId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.parentId, other.parentId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.content, other.content) != 0) {
      return false;
    }
    if (this.createdAt != other.createdAt) {
      return false;
    }
    return true;
  }
}










