/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Group extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3556158056636443879L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Group\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"Group ID as primary key\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\",\"doc\":\"Unique code for joining the group\"},{\"name\":\"hidden\",\"type\":\"boolean\",\"default\":false},{\"name\":\"createdBy\",\"type\":\"long\",\"doc\":\"User ID who created the group\"},{\"name\":\"createdAt\",\"type\":[\"null\",\"long\"],\"doc\":\"Creation timestamp\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Group> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Group> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Group> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Group> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Group> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Group to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Group from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Group instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Group fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Group ID as primary key */
  private long id;
  private CharSequence name;
  /** Unique code for joining the group */
  private CharSequence code;
  private boolean hidden;
  /** User ID who created the group */
  private long createdBy;
  /** Creation timestamp */
  private Long createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Group() {}

  /**
   * All-args constructor.
   * @param id Group ID as primary key
   * @param name The new value for name
   * @param code Unique code for joining the group
   * @param hidden The new value for hidden
   * @param createdBy User ID who created the group
   * @param createdAt Creation timestamp
   */
  public Group(Long id, CharSequence name, CharSequence code, Boolean hidden, Long createdBy, Long createdAt) {
    this.id = id;
    this.name = name;
    this.code = code;
    this.hidden = hidden;
    this.createdBy = createdBy;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return code;
    case 3: return hidden;
    case 4: return createdBy;
    case 5: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (Long)value$; break;
    case 1: name = (CharSequence)value$; break;
    case 2: code = (CharSequence)value$; break;
    case 3: hidden = (Boolean)value$; break;
    case 4: createdBy = (Long)value$; break;
    case 5: createdAt = (Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Group ID as primary key
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Group ID as primary key
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return Unique code for joining the group
   */
  public CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * Unique code for joining the group
   * @param value the value to set.
   */
  public void setCode(CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'hidden' field.
   * @return The value of the 'hidden' field.
   */
  public boolean getHidden() {
    return hidden;
  }


  /**
   * Sets the value of the 'hidden' field.
   * @param value the value to set.
   */
  public void setHidden(boolean value) {
    this.hidden = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return User ID who created the group
   */
  public long getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * User ID who created the group
   * @param value the value to set.
   */
  public void setCreatedBy(long value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Creation timestamp
   */
  public Long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Creation timestamp
   * @param value the value to set.
   */
  public void setCreatedAt(Long value) {
    this.createdAt = value;
  }

  /**
   * Creates a new Group RecordBuilder.
   * @return A new Group RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Group RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Group RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Group RecordBuilder by copying an existing Group instance.
   * @param other The existing instance to copy.
   * @return A new Group RecordBuilder
   */
  public static Builder newBuilder(Group other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Group instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Group>
    implements org.apache.avro.data.RecordBuilder<Group> {

    /** Group ID as primary key */
    private long id;
    private CharSequence name;
    /** Unique code for joining the group */
    private CharSequence code;
    private boolean hidden;
    /** User ID who created the group */
    private long createdBy;
    /** Creation timestamp */
    private Long createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.hidden)) {
        this.hidden = data().deepCopy(fields()[3].schema(), other.hidden);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[4].schema(), other.createdBy);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Group instance
     * @param other The existing instance to copy.
     */
    private Builder(Group other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.hidden)) {
        this.hidden = data().deepCopy(fields()[3].schema(), other.hidden);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[4].schema(), other.createdBy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Group ID as primary key
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Group ID as primary key
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Group ID as primary key
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Group ID as primary key
      * @return This builder.
      */
    public Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public Builder setName(CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * Unique code for joining the group
      * @return The value.
      */
    public CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * Unique code for joining the group
      * @param value The value of 'code'.
      * @return This builder.
      */
    public Builder setCode(CharSequence value) {
      validate(fields()[2], value);
      this.code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * Unique code for joining the group
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'code' field.
      * Unique code for joining the group
      * @return This builder.
      */
    public Builder clearCode() {
      code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'hidden' field.
      * @return The value.
      */
    public boolean getHidden() {
      return hidden;
    }


    /**
      * Sets the value of the 'hidden' field.
      * @param value The value of 'hidden'.
      * @return This builder.
      */
    public Builder setHidden(boolean value) {
      validate(fields()[3], value);
      this.hidden = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'hidden' field has been set.
      * @return True if the 'hidden' field has been set, false otherwise.
      */
    public boolean hasHidden() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'hidden' field.
      * @return This builder.
      */
    public Builder clearHidden() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * User ID who created the group
      * @return The value.
      */
    public long getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * User ID who created the group
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public Builder setCreatedBy(long value) {
      validate(fields()[4], value);
      this.createdBy = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * User ID who created the group
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * User ID who created the group
      * @return This builder.
      */
    public Builder clearCreatedBy() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Creation timestamp
      * @return The value.
      */
    public Long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Creation timestamp
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public Builder setCreatedAt(Long value) {
      validate(fields()[5], value);
      this.createdAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Creation timestamp
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Creation timestamp
      * @return This builder.
      */
    public Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Group build() {
      try {
        Group record = new Group();
        record.id = fieldSetFlags()[0] ? this.id : (Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (CharSequence) defaultValue(fields()[1]);
        record.code = fieldSetFlags()[2] ? this.code : (CharSequence) defaultValue(fields()[2]);
        record.hidden = fieldSetFlags()[3] ? this.hidden : (Boolean) defaultValue(fields()[3]);
        record.createdBy = fieldSetFlags()[4] ? this.createdBy : (Long) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Group>
    WRITER$ = (org.apache.avro.io.DatumWriter<Group>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Group>
    READER$ = (org.apache.avro.io.DatumReader<Group>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeString(this.code);

    out.writeBoolean(this.hidden);

    out.writeLong(this.createdBy);

    if (this.createdAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.createdAt);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.hidden = in.readBoolean();

      this.createdBy = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.createdAt = null;
      } else {
        this.createdAt = in.readLong();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 3:
          this.hidden = in.readBoolean();
          break;

        case 4:
          this.createdBy = in.readLong();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.createdAt = null;
          } else {
            this.createdAt = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Long.hashCode(id);
    result = 31 * result + (name == null ? 0 : name.hashCode());
    result = 31 * result + (code == null ? 0 : code.hashCode());
    result = 31 * result + Boolean.hashCode(hidden);
    result = 31 * result + Long.hashCode(createdBy);
    result = 31 * result + (createdAt == null ? 0 : createdAt.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Group)) {
      return false;
    }
    Group other = (Group) o;
    if (this.id != other.id) {
      return false;
    }
    if (Utf8.compareSequences(this.name, other.name) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.code, other.code) != 0) {
      return false;
    }
    if (this.hidden != other.hidden) {
      return false;
    }
    if (this.createdBy != other.createdBy) {
      return false;
    }
    if (!java.util.Objects.equals(this.createdAt, other.createdAt)) {
      return false;
    }
    return true;
  }
}










