/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Group extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -235230582978598362L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Group\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"hidden\",\"type\":\"boolean\",\"default\":false},{\"name\":\"owner\",\"type\":\"string\",\"doc\":\"email of the user who created the group\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Group> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Group> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Group> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Group> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Group> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Group to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Group from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Group instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Group fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence name;
  private boolean hidden;
  /** email of the user who created the group */
  private java.lang.CharSequence owner;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Group() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param hidden The new value for hidden
   * @param owner email of the user who created the group
   */
  public Group(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.Boolean hidden, java.lang.CharSequence owner) {
    this.id = id;
    this.name = name;
    this.hidden = hidden;
    this.owner = owner;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return hidden;
    case 3: return owner;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: hidden = (java.lang.Boolean)value$; break;
    case 3: owner = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'hidden' field.
   * @return The value of the 'hidden' field.
   */
  public boolean getHidden() {
    return hidden;
  }


  /**
   * Sets the value of the 'hidden' field.
   * @param value the value to set.
   */
  public void setHidden(boolean value) {
    this.hidden = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return email of the user who created the group
   */
  public java.lang.CharSequence getOwner() {
    return owner;
  }


  /**
   * Sets the value of the 'owner' field.
   * email of the user who created the group
   * @param value the value to set.
   */
  public void setOwner(java.lang.CharSequence value) {
    this.owner = value;
  }

  /**
   * Creates a new Group RecordBuilder.
   * @return A new Group RecordBuilder
   */
  public static com.example.mediaservice.entity.Group.Builder newBuilder() {
    return new com.example.mediaservice.entity.Group.Builder();
  }

  /**
   * Creates a new Group RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Group RecordBuilder
   */
  public static com.example.mediaservice.entity.Group.Builder newBuilder(com.example.mediaservice.entity.Group.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Group.Builder();
    } else {
      return new com.example.mediaservice.entity.Group.Builder(other);
    }
  }

  /**
   * Creates a new Group RecordBuilder by copying an existing Group instance.
   * @param other The existing instance to copy.
   * @return A new Group RecordBuilder
   */
  public static com.example.mediaservice.entity.Group.Builder newBuilder(com.example.mediaservice.entity.Group other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Group.Builder();
    } else {
      return new com.example.mediaservice.entity.Group.Builder(other);
    }
  }

  /**
   * RecordBuilder for Group instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Group>
    implements org.apache.avro.data.RecordBuilder<Group> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private boolean hidden;
    /** email of the user who created the group */
    private java.lang.CharSequence owner;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.Group.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.hidden)) {
        this.hidden = data().deepCopy(fields()[2].schema(), other.hidden);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Group instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.Group other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.hidden)) {
        this.hidden = data().deepCopy(fields()[2].schema(), other.hidden);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'hidden' field.
      * @return The value.
      */
    public boolean getHidden() {
      return hidden;
    }


    /**
      * Sets the value of the 'hidden' field.
      * @param value The value of 'hidden'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder setHidden(boolean value) {
      validate(fields()[2], value);
      this.hidden = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'hidden' field has been set.
      * @return True if the 'hidden' field has been set, false otherwise.
      */
    public boolean hasHidden() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'hidden' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder clearHidden() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * email of the user who created the group
      * @return The value.
      */
    public java.lang.CharSequence getOwner() {
      return owner;
    }


    /**
      * Sets the value of the 'owner' field.
      * email of the user who created the group
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder setOwner(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.owner = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * email of the user who created the group
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'owner' field.
      * email of the user who created the group
      * @return This builder.
      */
    public com.example.mediaservice.entity.Group.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Group build() {
      try {
        Group record = new Group();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.hidden = fieldSetFlags()[2] ? this.hidden : (java.lang.Boolean) defaultValue(fields()[2]);
        record.owner = fieldSetFlags()[3] ? this.owner : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Group>
    WRITER$ = (org.apache.avro.io.DatumWriter<Group>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Group>
    READER$ = (org.apache.avro.io.DatumReader<Group>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.name);

    out.writeBoolean(this.hidden);

    out.writeString(this.owner);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.hidden = in.readBoolean();

      this.owner = in.readString(this.owner instanceof Utf8 ? (Utf8)this.owner : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.hidden = in.readBoolean();
          break;

        case 3:
          this.owner = in.readString(this.owner instanceof Utf8 ? (Utf8)this.owner : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (name == null ? 0 : name.hashCode());
    result = 31 * result + Boolean.hashCode(hidden);
    result = 31 * result + (owner == null ? 0 : owner.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Group)) {
      return false;
    }
    Group other = (Group) o;
    if (Utf8.compareSequences(this.id, other.id) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.name, other.name) != 0) {
      return false;
    }
    if (this.hidden != other.hidden) {
      return false;
    }
    if (Utf8.compareSequences(this.owner, other.owner) != 0) {
      return false;
    }
    return true;
  }
}










