/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Post extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6713198825530385722L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Post\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"Post ID as primary key\"},{\"name\":\"groupId\",\"type\":\"string\",\"doc\":\"Group ID that this post belongs to\"},{\"name\":\"channelId\",\"type\":[\"null\",\"string\"],\"doc\":\"Optional channel ID if posted in a channel\",\"default\":null},{\"name\":\"author\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"email\",\"type\":\"string\",\"doc\":\"Email as primary key\"},{\"name\":\"dateOfBirth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"avatarUrl\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"occupation\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"version\",\"type\":[\"null\",\"int\"],\"doc\":\"Version for optimistic locking\",\"default\":null}]}],\"doc\":\"Email of the post author\",\"default\":null},{\"name\":\"content\",\"type\":\"string\",\"doc\":\"Post content\"},{\"name\":\"likes\",\"type\":\"int\",\"doc\":\"Number of likes\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Post> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Post> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Post> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Post> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Post> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Post to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Post from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Post instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Post fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Post ID as primary key */
  private java.lang.CharSequence id;
  /** Group ID that this post belongs to */
  private java.lang.CharSequence groupId;
  /** Optional channel ID if posted in a channel */
  private java.lang.CharSequence channelId;
  /** Email of the post author */
  private com.example.mediaservice.entity.User author;
  /** Post content */
  private java.lang.CharSequence content;
  /** Number of likes */
  private int likes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Post() {}

  /**
   * All-args constructor.
   * @param id Post ID as primary key
   * @param groupId Group ID that this post belongs to
   * @param channelId Optional channel ID if posted in a channel
   * @param author Email of the post author
   * @param content Post content
   * @param likes Number of likes
   */
  public Post(java.lang.CharSequence id, java.lang.CharSequence groupId, java.lang.CharSequence channelId, com.example.mediaservice.entity.User author, java.lang.CharSequence content, java.lang.Integer likes) {
    this.id = id;
    this.groupId = groupId;
    this.channelId = channelId;
    this.author = author;
    this.content = content;
    this.likes = likes;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return groupId;
    case 2: return channelId;
    case 3: return author;
    case 4: return content;
    case 5: return likes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: groupId = (java.lang.CharSequence)value$; break;
    case 2: channelId = (java.lang.CharSequence)value$; break;
    case 3: author = (com.example.mediaservice.entity.User)value$; break;
    case 4: content = (java.lang.CharSequence)value$; break;
    case 5: likes = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Post ID as primary key
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Post ID as primary key
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return Group ID that this post belongs to
   */
  public java.lang.CharSequence getGroupId() {
    return groupId;
  }


  /**
   * Sets the value of the 'groupId' field.
   * Group ID that this post belongs to
   * @param value the value to set.
   */
  public void setGroupId(java.lang.CharSequence value) {
    this.groupId = value;
  }

  /**
   * Gets the value of the 'channelId' field.
   * @return Optional channel ID if posted in a channel
   */
  public java.lang.CharSequence getChannelId() {
    return channelId;
  }


  /**
   * Sets the value of the 'channelId' field.
   * Optional channel ID if posted in a channel
   * @param value the value to set.
   */
  public void setChannelId(java.lang.CharSequence value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'author' field.
   * @return Email of the post author
   */
  public com.example.mediaservice.entity.User getAuthor() {
    return author;
  }


  /**
   * Sets the value of the 'author' field.
   * Email of the post author
   * @param value the value to set.
   */
  public void setAuthor(com.example.mediaservice.entity.User value) {
    this.author = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return Post content
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * Post content
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'likes' field.
   * @return Number of likes
   */
  public int getLikes() {
    return likes;
  }


  /**
   * Sets the value of the 'likes' field.
   * Number of likes
   * @param value the value to set.
   */
  public void setLikes(int value) {
    this.likes = value;
  }

  /**
   * Creates a new Post RecordBuilder.
   * @return A new Post RecordBuilder
   */
  public static com.example.mediaservice.entity.Post.Builder newBuilder() {
    return new com.example.mediaservice.entity.Post.Builder();
  }

  /**
   * Creates a new Post RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Post RecordBuilder
   */
  public static com.example.mediaservice.entity.Post.Builder newBuilder(com.example.mediaservice.entity.Post.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Post.Builder();
    } else {
      return new com.example.mediaservice.entity.Post.Builder(other);
    }
  }

  /**
   * Creates a new Post RecordBuilder by copying an existing Post instance.
   * @param other The existing instance to copy.
   * @return A new Post RecordBuilder
   */
  public static com.example.mediaservice.entity.Post.Builder newBuilder(com.example.mediaservice.entity.Post other) {
    if (other == null) {
      return new com.example.mediaservice.entity.Post.Builder();
    } else {
      return new com.example.mediaservice.entity.Post.Builder(other);
    }
  }

  /**
   * RecordBuilder for Post instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Post>
    implements org.apache.avro.data.RecordBuilder<Post> {

    /** Post ID as primary key */
    private java.lang.CharSequence id;
    /** Group ID that this post belongs to */
    private java.lang.CharSequence groupId;
    /** Optional channel ID if posted in a channel */
    private java.lang.CharSequence channelId;
    /** Email of the post author */
    private com.example.mediaservice.entity.User author;
    private com.example.mediaservice.entity.User.Builder authorBuilder;
    /** Post content */
    private java.lang.CharSequence content;
    /** Number of likes */
    private int likes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.Post.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.channelId)) {
        this.channelId = data().deepCopy(fields()[2].schema(), other.channelId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.author)) {
        this.author = data().deepCopy(fields()[3].schema(), other.author);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasAuthorBuilder()) {
        this.authorBuilder = com.example.mediaservice.entity.User.newBuilder(other.getAuthorBuilder());
      }
      if (isValidValue(fields()[4], other.content)) {
        this.content = data().deepCopy(fields()[4].schema(), other.content);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.likes)) {
        this.likes = data().deepCopy(fields()[5].schema(), other.likes);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Post instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.Post other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groupId)) {
        this.groupId = data().deepCopy(fields()[1].schema(), other.groupId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.channelId)) {
        this.channelId = data().deepCopy(fields()[2].schema(), other.channelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.author)) {
        this.author = data().deepCopy(fields()[3].schema(), other.author);
        fieldSetFlags()[3] = true;
      }
      this.authorBuilder = null;
      if (isValidValue(fields()[4], other.content)) {
        this.content = data().deepCopy(fields()[4].schema(), other.content);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.likes)) {
        this.likes = data().deepCopy(fields()[5].schema(), other.likes);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Post ID as primary key
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Post ID as primary key
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Post ID as primary key
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Post ID as primary key
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groupId' field.
      * Group ID that this post belongs to
      * @return The value.
      */
    public java.lang.CharSequence getGroupId() {
      return groupId;
    }


    /**
      * Sets the value of the 'groupId' field.
      * Group ID that this post belongs to
      * @param value The value of 'groupId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setGroupId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.groupId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groupId' field has been set.
      * Group ID that this post belongs to
      * @return True if the 'groupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groupId' field.
      * Group ID that this post belongs to
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearGroupId() {
      groupId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'channelId' field.
      * Optional channel ID if posted in a channel
      * @return The value.
      */
    public java.lang.CharSequence getChannelId() {
      return channelId;
    }


    /**
      * Sets the value of the 'channelId' field.
      * Optional channel ID if posted in a channel
      * @param value The value of 'channelId'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setChannelId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.channelId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'channelId' field has been set.
      * Optional channel ID if posted in a channel
      * @return True if the 'channelId' field has been set, false otherwise.
      */
    public boolean hasChannelId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'channelId' field.
      * Optional channel ID if posted in a channel
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'author' field.
      * Email of the post author
      * @return The value.
      */
    public com.example.mediaservice.entity.User getAuthor() {
      return author;
    }


    /**
      * Sets the value of the 'author' field.
      * Email of the post author
      * @param value The value of 'author'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setAuthor(com.example.mediaservice.entity.User value) {
      validate(fields()[3], value);
      this.authorBuilder = null;
      this.author = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'author' field has been set.
      * Email of the post author
      * @return True if the 'author' field has been set, false otherwise.
      */
    public boolean hasAuthor() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'author' field and creates one if it doesn't exist yet.
     * Email of the post author
     * @return This builder.
     */
    public com.example.mediaservice.entity.User.Builder getAuthorBuilder() {
      if (authorBuilder == null) {
        if (hasAuthor()) {
          setAuthorBuilder(com.example.mediaservice.entity.User.newBuilder(author));
        } else {
          setAuthorBuilder(com.example.mediaservice.entity.User.newBuilder());
        }
      }
      return authorBuilder;
    }

    /**
     * Sets the Builder instance for the 'author' field
     * Email of the post author
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.mediaservice.entity.Post.Builder setAuthorBuilder(com.example.mediaservice.entity.User.Builder value) {
      clearAuthor();
      authorBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'author' field has an active Builder instance
     * Email of the post author
     * @return True if the 'author' field has an active Builder instance
     */
    public boolean hasAuthorBuilder() {
      return authorBuilder != null;
    }

    /**
      * Clears the value of the 'author' field.
      * Email of the post author
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearAuthor() {
      author = null;
      authorBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * Post content
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * Post content
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.content = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * Post content
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'content' field.
      * Post content
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearContent() {
      content = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'likes' field.
      * Number of likes
      * @return The value.
      */
    public int getLikes() {
      return likes;
    }


    /**
      * Sets the value of the 'likes' field.
      * Number of likes
      * @param value The value of 'likes'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder setLikes(int value) {
      validate(fields()[5], value);
      this.likes = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'likes' field has been set.
      * Number of likes
      * @return True if the 'likes' field has been set, false otherwise.
      */
    public boolean hasLikes() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'likes' field.
      * Number of likes
      * @return This builder.
      */
    public com.example.mediaservice.entity.Post.Builder clearLikes() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Post build() {
      try {
        Post record = new Post();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.groupId = fieldSetFlags()[1] ? this.groupId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.channelId = fieldSetFlags()[2] ? this.channelId : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (authorBuilder != null) {
          try {
            record.author = this.authorBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("author"));
            throw e;
          }
        } else {
          record.author = fieldSetFlags()[3] ? this.author : (com.example.mediaservice.entity.User) defaultValue(fields()[3]);
        }
        record.content = fieldSetFlags()[4] ? this.content : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.likes = fieldSetFlags()[5] ? this.likes : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Post>
    WRITER$ = (org.apache.avro.io.DatumWriter<Post>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Post>
    READER$ = (org.apache.avro.io.DatumReader<Post>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.groupId);

    if (this.channelId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.channelId);
    }

    if (this.author == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.author.customEncode(out);
    }

    out.writeString(this.content);

    out.writeInt(this.likes);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.channelId = null;
      } else {
        this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.author = null;
      } else {
        if (this.author == null) {
          this.author = new com.example.mediaservice.entity.User();
        }
        this.author.customDecode(in);
      }

      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

      this.likes = in.readInt();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.groupId = in.readString(this.groupId instanceof Utf8 ? (Utf8)this.groupId : null);
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.channelId = null;
          } else {
            this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.author = null;
          } else {
            if (this.author == null) {
              this.author = new com.example.mediaservice.entity.User();
            }
            this.author.customDecode(in);
          }
          break;

        case 4:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        case 5:
          this.likes = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (groupId == null ? 0 : groupId.hashCode());
    result = 31 * result + (channelId == null ? 0 : channelId.hashCode());
    result = 31 * result + (author == null ? 0 : author.hashCode());
    result = 31 * result + (content == null ? 0 : content.hashCode());
    result = 31 * result + Integer.hashCode(likes);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Post)) {
      return false;
    }
    Post other = (Post) o;
    if (Utf8.compareSequences(this.id, other.id) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.groupId, other.groupId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.channelId, other.channelId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.author, other.author)) {
      return false;
    }
    if (Utf8.compareSequences(this.content, other.content) != 0) {
      return false;
    }
    if (this.likes != other.likes) {
      return false;
    }
    return true;
  }
}










