/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1603778421123938887L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"email\",\"type\":\"string\",\"doc\":\"Email as primary key\"},{\"name\":\"dateOfBirth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"avatarUrl\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"occupation\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"version\",\"type\":[\"null\",\"int\"],\"doc\":\"Version for optimistic locking\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<User> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<User> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<User> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<User> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<User> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this User to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a User from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a User instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static User fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Email as primary key */
  private java.lang.CharSequence email;
  private java.lang.CharSequence dateOfBirth;
  private java.lang.CharSequence gender;
  private java.lang.CharSequence avatarUrl;
  private java.lang.CharSequence occupation;
  private java.lang.CharSequence firstName;
  private java.lang.CharSequence lastName;
  /** Version for optimistic locking */
  private java.lang.Integer version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User() {}

  /**
   * All-args constructor.
   * @param email Email as primary key
   * @param dateOfBirth The new value for dateOfBirth
   * @param gender The new value for gender
   * @param avatarUrl The new value for avatarUrl
   * @param occupation The new value for occupation
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param version Version for optimistic locking
   */
  public User(java.lang.CharSequence email, java.lang.CharSequence dateOfBirth, java.lang.CharSequence gender, java.lang.CharSequence avatarUrl, java.lang.CharSequence occupation, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.Integer version) {
    this.email = email;
    this.dateOfBirth = dateOfBirth;
    this.gender = gender;
    this.avatarUrl = avatarUrl;
    this.occupation = occupation;
    this.firstName = firstName;
    this.lastName = lastName;
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return email;
    case 1: return dateOfBirth;
    case 2: return gender;
    case 3: return avatarUrl;
    case 4: return occupation;
    case 5: return firstName;
    case 6: return lastName;
    case 7: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: email = (java.lang.CharSequence)value$; break;
    case 1: dateOfBirth = (java.lang.CharSequence)value$; break;
    case 2: gender = (java.lang.CharSequence)value$; break;
    case 3: avatarUrl = (java.lang.CharSequence)value$; break;
    case 4: occupation = (java.lang.CharSequence)value$; break;
    case 5: firstName = (java.lang.CharSequence)value$; break;
    case 6: lastName = (java.lang.CharSequence)value$; break;
    case 7: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'email' field.
   * @return Email as primary key
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * Email as primary key
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'dateOfBirth' field.
   * @return The value of the 'dateOfBirth' field.
   */
  public java.lang.CharSequence getDateOfBirth() {
    return dateOfBirth;
  }


  /**
   * Sets the value of the 'dateOfBirth' field.
   * @param value the value to set.
   */
  public void setDateOfBirth(java.lang.CharSequence value) {
    this.dateOfBirth = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public java.lang.CharSequence getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(java.lang.CharSequence value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'avatarUrl' field.
   * @return The value of the 'avatarUrl' field.
   */
  public java.lang.CharSequence getAvatarUrl() {
    return avatarUrl;
  }


  /**
   * Sets the value of the 'avatarUrl' field.
   * @param value the value to set.
   */
  public void setAvatarUrl(java.lang.CharSequence value) {
    this.avatarUrl = value;
  }

  /**
   * Gets the value of the 'occupation' field.
   * @return The value of the 'occupation' field.
   */
  public java.lang.CharSequence getOccupation() {
    return occupation;
  }


  /**
   * Sets the value of the 'occupation' field.
   * @param value the value to set.
   */
  public void setOccupation(java.lang.CharSequence value) {
    this.occupation = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return Version for optimistic locking
   */
  public java.lang.Integer getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * Version for optimistic locking
   * @param value the value to set.
   */
  public void setVersion(java.lang.Integer value) {
    this.version = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static com.example.mediaservice.entity.User.Builder newBuilder() {
    return new com.example.mediaservice.entity.User.Builder();
  }

  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static com.example.mediaservice.entity.User.Builder newBuilder(com.example.mediaservice.entity.User.Builder other) {
    if (other == null) {
      return new com.example.mediaservice.entity.User.Builder();
    } else {
      return new com.example.mediaservice.entity.User.Builder(other);
    }
  }

  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static com.example.mediaservice.entity.User.Builder newBuilder(com.example.mediaservice.entity.User other) {
    if (other == null) {
      return new com.example.mediaservice.entity.User.Builder();
    } else {
      return new com.example.mediaservice.entity.User.Builder(other);
    }
  }

  /**
   * RecordBuilder for User instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    /** Email as primary key */
    private java.lang.CharSequence email;
    private java.lang.CharSequence dateOfBirth;
    private java.lang.CharSequence gender;
    private java.lang.CharSequence avatarUrl;
    private java.lang.CharSequence occupation;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    /** Version for optimistic locking */
    private java.lang.Integer version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.mediaservice.entity.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.email)) {
        this.email = data().deepCopy(fields()[0].schema(), other.email);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.dateOfBirth)) {
        this.dateOfBirth = data().deepCopy(fields()[1].schema(), other.dateOfBirth);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.gender)) {
        this.gender = data().deepCopy(fields()[2].schema(), other.gender);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.avatarUrl)) {
        this.avatarUrl = data().deepCopy(fields()[3].schema(), other.avatarUrl);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.occupation)) {
        this.occupation = data().deepCopy(fields()[4].schema(), other.occupation);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.firstName)) {
        this.firstName = data().deepCopy(fields()[5].schema(), other.firstName);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.lastName)) {
        this.lastName = data().deepCopy(fields()[6].schema(), other.lastName);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.version)) {
        this.version = data().deepCopy(fields()[7].schema(), other.version);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.mediaservice.entity.User other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.email)) {
        this.email = data().deepCopy(fields()[0].schema(), other.email);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dateOfBirth)) {
        this.dateOfBirth = data().deepCopy(fields()[1].schema(), other.dateOfBirth);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.gender)) {
        this.gender = data().deepCopy(fields()[2].schema(), other.gender);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.avatarUrl)) {
        this.avatarUrl = data().deepCopy(fields()[3].schema(), other.avatarUrl);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.occupation)) {
        this.occupation = data().deepCopy(fields()[4].schema(), other.occupation);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.firstName)) {
        this.firstName = data().deepCopy(fields()[5].schema(), other.firstName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.lastName)) {
        this.lastName = data().deepCopy(fields()[6].schema(), other.lastName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.version)) {
        this.version = data().deepCopy(fields()[7].schema(), other.version);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'email' field.
      * Email as primary key
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * Email as primary key
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.email = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * Email as primary key
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'email' field.
      * Email as primary key
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearEmail() {
      email = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateOfBirth' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateOfBirth() {
      return dateOfBirth;
    }


    /**
      * Sets the value of the 'dateOfBirth' field.
      * @param value The value of 'dateOfBirth'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setDateOfBirth(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.dateOfBirth = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dateOfBirth' field has been set.
      * @return True if the 'dateOfBirth' field has been set, false otherwise.
      */
    public boolean hasDateOfBirth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dateOfBirth' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearDateOfBirth() {
      dateOfBirth = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public java.lang.CharSequence getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setGender(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.gender = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearGender() {
      gender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'avatarUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getAvatarUrl() {
      return avatarUrl;
    }


    /**
      * Sets the value of the 'avatarUrl' field.
      * @param value The value of 'avatarUrl'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setAvatarUrl(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.avatarUrl = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'avatarUrl' field has been set.
      * @return True if the 'avatarUrl' field has been set, false otherwise.
      */
    public boolean hasAvatarUrl() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'avatarUrl' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearAvatarUrl() {
      avatarUrl = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'occupation' field.
      * @return The value.
      */
    public java.lang.CharSequence getOccupation() {
      return occupation;
    }


    /**
      * Sets the value of the 'occupation' field.
      * @param value The value of 'occupation'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setOccupation(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.occupation = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'occupation' field has been set.
      * @return True if the 'occupation' field has been set, false otherwise.
      */
    public boolean hasOccupation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'occupation' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearOccupation() {
      occupation = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.firstName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.lastName = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * Version for optimistic locking
      * @return The value.
      */
    public java.lang.Integer getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * Version for optimistic locking
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder setVersion(java.lang.Integer value) {
      validate(fields()[7], value);
      this.version = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * Version for optimistic locking
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'version' field.
      * Version for optimistic locking
      * @return This builder.
      */
    public com.example.mediaservice.entity.User.Builder clearVersion() {
      version = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public User build() {
      try {
        User record = new User();
        record.email = fieldSetFlags()[0] ? this.email : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.dateOfBirth = fieldSetFlags()[1] ? this.dateOfBirth : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.gender = fieldSetFlags()[2] ? this.gender : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.avatarUrl = fieldSetFlags()[3] ? this.avatarUrl : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.occupation = fieldSetFlags()[4] ? this.occupation : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.firstName = fieldSetFlags()[5] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.lastName = fieldSetFlags()[6] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.version = fieldSetFlags()[7] ? this.version : (java.lang.Integer) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<User>
    WRITER$ = (org.apache.avro.io.DatumWriter<User>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<User>
    READER$ = (org.apache.avro.io.DatumReader<User>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.email);

    if (this.dateOfBirth == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dateOfBirth);
    }

    out.writeString(this.gender);

    if (this.avatarUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.avatarUrl);
    }

    out.writeString(this.occupation);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    if (this.version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.version);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.dateOfBirth = null;
      } else {
        this.dateOfBirth = in.readString(this.dateOfBirth instanceof Utf8 ? (Utf8)this.dateOfBirth : null);
      }

      this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.avatarUrl = null;
      } else {
        this.avatarUrl = in.readString(this.avatarUrl instanceof Utf8 ? (Utf8)this.avatarUrl : null);
      }

      this.occupation = in.readString(this.occupation instanceof Utf8 ? (Utf8)this.occupation : null);

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.version = null;
      } else {
        this.version = in.readInt();
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dateOfBirth = null;
          } else {
            this.dateOfBirth = in.readString(this.dateOfBirth instanceof Utf8 ? (Utf8)this.dateOfBirth : null);
          }
          break;

        case 2:
          this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.avatarUrl = null;
          } else {
            this.avatarUrl = in.readString(this.avatarUrl instanceof Utf8 ? (Utf8)this.avatarUrl : null);
          }
          break;

        case 4:
          this.occupation = in.readString(this.occupation instanceof Utf8 ? (Utf8)this.occupation : null);
          break;

        case 5:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 6:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.version = null;
          } else {
            this.version = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (email == null ? 0 : email.hashCode());
    result = 31 * result + (dateOfBirth == null ? 0 : dateOfBirth.hashCode());
    result = 31 * result + (gender == null ? 0 : gender.hashCode());
    result = 31 * result + (avatarUrl == null ? 0 : avatarUrl.hashCode());
    result = 31 * result + (occupation == null ? 0 : occupation.hashCode());
    result = 31 * result + (firstName == null ? 0 : firstName.hashCode());
    result = 31 * result + (lastName == null ? 0 : lastName.hashCode());
    result = 31 * result + (version == null ? 0 : version.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof User)) {
      return false;
    }
    User other = (User) o;
    if (Utf8.compareSequences(this.email, other.email) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.dateOfBirth, other.dateOfBirth) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.gender, other.gender) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.avatarUrl, other.avatarUrl) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.occupation, other.occupation) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.firstName, other.firstName) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.lastName, other.lastName) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.version, other.version)) {
      return false;
    }
    return true;
  }
}










