/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.mediaservice.entity;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -546109810338936201L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.example.mediaservice.entity\",\"fields\":[{\"name\":\"email\",\"type\":\"string\",\"doc\":\"Email as primary key\"},{\"name\":\"dateOfBirth\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"version\",\"type\":[\"null\",\"int\"],\"doc\":\"Version for optimistic locking\",\"default\":null},{\"name\":\"createdAt\",\"type\":[\"null\",\"long\"],\"doc\":\"Creation timestamp\",\"default\":null},{\"name\":\"lastModified\",\"type\":[\"null\",\"long\"],\"doc\":\"Last modified timestamp\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<User> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<User> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<User> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<User> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<User> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this User to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a User from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a User instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static User fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Email as primary key */
  private CharSequence email;
  private CharSequence dateOfBirth;
  private CharSequence gender;
  private CharSequence firstName;
  private CharSequence lastName;
  /** Version for optimistic locking */
  private Integer version;
  /** Creation timestamp */
  private Long createdAt;
  /** Last modified timestamp */
  private Long lastModified;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User() {}

  /**
   * All-args constructor.
   * @param email Email as primary key
   * @param dateOfBirth The new value for dateOfBirth
   * @param gender The new value for gender
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param version Version for optimistic locking
   * @param createdAt Creation timestamp
   * @param lastModified Last modified timestamp
   */
  public User(CharSequence email, CharSequence dateOfBirth, CharSequence gender, CharSequence firstName, CharSequence lastName, Integer version, Long createdAt, Long lastModified) {
    this.email = email;
    this.dateOfBirth = dateOfBirth;
    this.gender = gender;
    this.firstName = firstName;
    this.lastName = lastName;
    this.version = version;
    this.createdAt = createdAt;
    this.lastModified = lastModified;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return email;
    case 1: return dateOfBirth;
    case 2: return gender;
    case 3: return firstName;
    case 4: return lastName;
    case 5: return version;
    case 6: return createdAt;
    case 7: return lastModified;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: email = (CharSequence)value$; break;
    case 1: dateOfBirth = (CharSequence)value$; break;
    case 2: gender = (CharSequence)value$; break;
    case 3: firstName = (CharSequence)value$; break;
    case 4: lastName = (CharSequence)value$; break;
    case 5: version = (Integer)value$; break;
    case 6: createdAt = (Long)value$; break;
    case 7: lastModified = (Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'email' field.
   * @return Email as primary key
   */
  public CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * Email as primary key
   * @param value the value to set.
   */
  public void setEmail(CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'dateOfBirth' field.
   * @return The value of the 'dateOfBirth' field.
   */
  public CharSequence getDateOfBirth() {
    return dateOfBirth;
  }


  /**
   * Sets the value of the 'dateOfBirth' field.
   * @param value the value to set.
   */
  public void setDateOfBirth(CharSequence value) {
    this.dateOfBirth = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public CharSequence getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(CharSequence value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return Version for optimistic locking
   */
  public Integer getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * Version for optimistic locking
   * @param value the value to set.
   */
  public void setVersion(Integer value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Creation timestamp
   */
  public Long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Creation timestamp
   * @param value the value to set.
   */
  public void setCreatedAt(Long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'lastModified' field.
   * @return Last modified timestamp
   */
  public Long getLastModified() {
    return lastModified;
  }


  /**
   * Sets the value of the 'lastModified' field.
   * Last modified timestamp
   * @param value the value to set.
   */
  public void setLastModified(Long value) {
    this.lastModified = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder(User other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for User instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    /** Email as primary key */
    private CharSequence email;
    private CharSequence dateOfBirth;
    private CharSequence gender;
    private CharSequence firstName;
    private CharSequence lastName;
    /** Version for optimistic locking */
    private Integer version;
    /** Creation timestamp */
    private Long createdAt;
    /** Last modified timestamp */
    private Long lastModified;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.email)) {
        this.email = data().deepCopy(fields()[0].schema(), other.email);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.dateOfBirth)) {
        this.dateOfBirth = data().deepCopy(fields()[1].schema(), other.dateOfBirth);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.gender)) {
        this.gender = data().deepCopy(fields()[2].schema(), other.gender);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lastModified)) {
        this.lastModified = data().deepCopy(fields()[7].schema(), other.lastModified);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(User other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.email)) {
        this.email = data().deepCopy(fields()[0].schema(), other.email);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dateOfBirth)) {
        this.dateOfBirth = data().deepCopy(fields()[1].schema(), other.dateOfBirth);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.gender)) {
        this.gender = data().deepCopy(fields()[2].schema(), other.gender);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastModified)) {
        this.lastModified = data().deepCopy(fields()[7].schema(), other.lastModified);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'email' field.
      * Email as primary key
      * @return The value.
      */
    public CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * Email as primary key
      * @param value The value of 'email'.
      * @return This builder.
      */
    public Builder setEmail(CharSequence value) {
      validate(fields()[0], value);
      this.email = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * Email as primary key
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'email' field.
      * Email as primary key
      * @return This builder.
      */
    public Builder clearEmail() {
      email = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateOfBirth' field.
      * @return The value.
      */
    public CharSequence getDateOfBirth() {
      return dateOfBirth;
    }


    /**
      * Sets the value of the 'dateOfBirth' field.
      * @param value The value of 'dateOfBirth'.
      * @return This builder.
      */
    public Builder setDateOfBirth(CharSequence value) {
      validate(fields()[1], value);
      this.dateOfBirth = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dateOfBirth' field has been set.
      * @return True if the 'dateOfBirth' field has been set, false otherwise.
      */
    public boolean hasDateOfBirth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dateOfBirth' field.
      * @return This builder.
      */
    public Builder clearDateOfBirth() {
      dateOfBirth = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public CharSequence getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public Builder setGender(CharSequence value) {
      validate(fields()[2], value);
      this.gender = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public Builder clearGender() {
      gender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public Builder setFirstName(CharSequence value) {
      validate(fields()[3], value);
      this.firstName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public Builder setLastName(CharSequence value) {
      validate(fields()[4], value);
      this.lastName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * Version for optimistic locking
      * @return The value.
      */
    public Integer getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * Version for optimistic locking
      * @param value The value of 'version'.
      * @return This builder.
      */
    public Builder setVersion(Integer value) {
      validate(fields()[5], value);
      this.version = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * Version for optimistic locking
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'version' field.
      * Version for optimistic locking
      * @return This builder.
      */
    public Builder clearVersion() {
      version = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Creation timestamp
      * @return The value.
      */
    public Long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Creation timestamp
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public Builder setCreatedAt(Long value) {
      validate(fields()[6], value);
      this.createdAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Creation timestamp
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Creation timestamp
      * @return This builder.
      */
    public Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModified' field.
      * Last modified timestamp
      * @return The value.
      */
    public Long getLastModified() {
      return lastModified;
    }


    /**
      * Sets the value of the 'lastModified' field.
      * Last modified timestamp
      * @param value The value of 'lastModified'.
      * @return This builder.
      */
    public Builder setLastModified(Long value) {
      validate(fields()[7], value);
      this.lastModified = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModified' field has been set.
      * Last modified timestamp
      * @return True if the 'lastModified' field has been set, false otherwise.
      */
    public boolean hasLastModified() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lastModified' field.
      * Last modified timestamp
      * @return This builder.
      */
    public Builder clearLastModified() {
      lastModified = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public User build() {
      try {
        User record = new User();
        record.email = fieldSetFlags()[0] ? this.email : (CharSequence) defaultValue(fields()[0]);
        record.dateOfBirth = fieldSetFlags()[1] ? this.dateOfBirth : (CharSequence) defaultValue(fields()[1]);
        record.gender = fieldSetFlags()[2] ? this.gender : (CharSequence) defaultValue(fields()[2]);
        record.firstName = fieldSetFlags()[3] ? this.firstName : (CharSequence) defaultValue(fields()[3]);
        record.lastName = fieldSetFlags()[4] ? this.lastName : (CharSequence) defaultValue(fields()[4]);
        record.version = fieldSetFlags()[5] ? this.version : (Integer) defaultValue(fields()[5]);
        record.createdAt = fieldSetFlags()[6] ? this.createdAt : (Long) defaultValue(fields()[6]);
        record.lastModified = fieldSetFlags()[7] ? this.lastModified : (Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<User>
    WRITER$ = (org.apache.avro.io.DatumWriter<User>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<User>
    READER$ = (org.apache.avro.io.DatumReader<User>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.email);

    out.writeString(this.dateOfBirth);

    out.writeString(this.gender);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    if (this.version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.version);
    }

    if (this.createdAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.createdAt);
    }

    if (this.lastModified == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.lastModified);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.dateOfBirth = in.readString(this.dateOfBirth instanceof Utf8 ? (Utf8)this.dateOfBirth : null);

      this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.version = null;
      } else {
        this.version = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.createdAt = null;
      } else {
        this.createdAt = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lastModified = null;
      } else {
        this.lastModified = in.readLong();
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 1:
          this.dateOfBirth = in.readString(this.dateOfBirth instanceof Utf8 ? (Utf8)this.dateOfBirth : null);
          break;

        case 2:
          this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);
          break;

        case 3:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 4:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.version = null;
          } else {
            this.version = in.readInt();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.createdAt = null;
          } else {
            this.createdAt = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lastModified = null;
          } else {
            this.lastModified = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (email == null ? 0 : email.hashCode());
    result = 31 * result + (dateOfBirth == null ? 0 : dateOfBirth.hashCode());
    result = 31 * result + (gender == null ? 0 : gender.hashCode());
    result = 31 * result + (firstName == null ? 0 : firstName.hashCode());
    result = 31 * result + (lastName == null ? 0 : lastName.hashCode());
    result = 31 * result + (version == null ? 0 : version.hashCode());
    result = 31 * result + (createdAt == null ? 0 : createdAt.hashCode());
    result = 31 * result + (lastModified == null ? 0 : lastModified.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof User)) {
      return false;
    }
    User other = (User) o;
    if (Utf8.compareSequences(this.email, other.email) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.dateOfBirth, other.dateOfBirth) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.gender, other.gender) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.firstName, other.firstName) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.lastName, other.lastName) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.version, other.version)) {
      return false;
    }
    if (!java.util.Objects.equals(this.createdAt, other.createdAt)) {
      return false;
    }
    if (!java.util.Objects.equals(this.lastModified, other.lastModified)) {
      return false;
    }
    return true;
  }
}










